# Test your FastAPI endpoints

GET http://127.0.0.1:80
Accept: application/json

###

GET http://127.0.0.1:80/api/v1.0/current/Москва
Accept: application/json

###

GET http://127.0.0.1:80/api/v1.0/current/Грузия?lang=en&units=standard
Accept: application/json

###

GET http://127.0.0.1:80/api/v1.0/current/London?lang=fr
Accept: application/json

###

GET http://127.0.0.1:80/api/v1.0/current/Екатеринбург?units=standard
Accept: application/json

###
